image: node:14

stages:
  - lint
  - audit
  - run

lint:
  except:
    - schedules
  stage: lint
  before_script:
    - npm install
  script:
    - npm run lint:ci

audit:
  except:
    - schedules
  stage: audit
  before_script:
    - npm install
  script:
    - npm audit

run:
  only:
    - schedules
  stage: run
  before_script:
    - npm install
  script:
    - npm run renovate
