image: node:14

stages:
  - Prepare
  - Lint
  - Dry-run
  - Security
  - Run

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules
  policy: pull

prepare:
  stage: Prepare
  cache:
    # inherit global_cache properties, override policy
    <<: *global_cache
    policy: pull-push
  before_script:
    - node --version
    - npm --version
  script:
    - npm install

lint:
  except:
    - schedules
  stage: Lint
  script:
    - npm run lint:ci

dry-run:
  except:
    - schedules
  stage: Dry-run
  script:
    - npm run renovate:dry-run

audit:
  except:
    - schedules
  stage: Security
  script:
    - npm audit

lockfile_lint:
  except:
    - schedules
  stage: Security
  script:
    - npm run lockfile-lint

run:
  only:
    refs:
      - schedules
    variables:
      - $IS_SNYK_RUN != "true"
  stage: Run
  script:
    - npm run renovate

snyk_test:
  only:
    refs:
      - schedules
    variables:
      - $IS_SNYK_RUN == "true" && $IS_WEEKLY_RUN != "true"
  stage: Security
  before_script:
    - npm run snyk:auth "$SNYK_TOKEN"
  script:
    - npm run snyk:test

snyk_monitor:
  only:
    refs:
      - schedules
    variables:
      - $IS_SNYK_RUN == "true" && $IS_WEEKLY_RUN == "true"
  stage: Security
  before_script:
    - npm run snyk:auth "$SNYK_TOKEN"
  script:
    - npm run snyk:monitor
