image: node:14

stages:
  - Prepare
  - Lint
  - Security
  - Run

cache: &global_cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules
  policy: pull

prepare:
  stage: Prepare
  cache:
    # inherit global_cache properties, override policy
    <<: *global_cache
    policy: pull-push
  script:
    - npm install

lint:
  except:
    - schedules
  stage: Lint
  script:
    - npm run lint:ci

audit:
  except:
    - schedules
  stage: Security
  script:
    - npm audit

lockfile_lint:
  except:
    - schedules
  stage: Security
  script:
    - npm run lockfile-lint

run:
  only:
    - schedules
  stage: Run
  script:
    - npm run renovate
